# Generated by Django 5.2.12 on 2026-04-18 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='rating',
            new_name='rating_3x3',
        ),
        migrations.AddField(
            model_name='profile',
            name='rating_4x4',
            field=models.IntegerField(default=1200),
        ),
        migrations.AddField(
            model_name='profile',
            name='rating_5x5',
            field=models.IntegerField(default=1200),
        ),
        migrations.CreateModel(
            name='MatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_size', models.IntegerField(default=3)),
                ('result', models.CharField(max_length=10)),
                ('rating_change', models.IntegerField(default=0)),
                ('new_rating', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('opponent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opponent_history', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
