# Generated by Django 5.2.12 on 2026-04-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_rating_profile_rating_3x3_profile_rating_4x4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rating_3x3',
            field=models.IntegerField(default=600),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rating_4x4',
            field=models.IntegerField(default=600),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rating_5x5',
            field=models.IntegerField(default=600),
        ),
    ]
