# Generated by Django 5.2.12 on 2026-04-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(default='_________', max_length=9)),
                ('current_player', models.CharField(default='X', max_length=1)),
                ('status', models.CharField(default='playing', max_length=10)),
                ('game_type', models.CharField(default='two_player_offline', max_length=20)),
            ],
        ),
    ]
