# Generated by Django 5.2.12 on 2026-04-18 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0002_game_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('enemy_hp', models.IntegerField()),
                ('ai_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_hp', models.IntegerField(default=20)),
                ('max_hp', models.IntegerField(default=20)),
                ('stage', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='enemy_hp',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='game',
            name='hazards',
            field=models.CharField(default='[]', max_length=255),
        ),
        migrations.AddField(
            model_name='game',
            name='player_hp',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='game',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tictactoe.encounter'),
        ),
        migrations.AddField(
            model_name='game',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tictactoe.run'),
        ),
    ]
